/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_tox_jtoxcore_JTox */

#ifndef _Included_im_tox_jtoxcore_JTox
#define _Included_im_tox_jtoxcore_JTox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxNew
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_im_tox_jtoxcore_JTox_toxNew
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxKill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxKill
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFinalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxGetSavedata
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxGetSavedata
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxBootstrap
 * Signature: (JLjava/lang/String;I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_im_tox_jtoxcore_JTox_toxBootstrap
  (JNIEnv *, jclass, jlong, jstring, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxAddTcpRelay
 * Signature: (JLjava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxAddTcpRelay
  (JNIEnv *, jclass, jlong, jstring, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetUdpPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetUdpPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetTcpPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetTcpPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetDhtId
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetDhtId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxIterationInterval
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxIterationInterval
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxIterate
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxIterate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetPublicKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetPublicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetSecretKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetSecretKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfSetNospam
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxSelfSetNospam
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetNospam
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetNospam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetAddress
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfSetName
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxSelfSetName
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetName
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfSetStatusMessage
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxSelfSetStatusMessage
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetStatusMessage
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetStatusMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfSetStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxSelfSetStatus
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendAdd
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxFriendAdd
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendAddNorequest
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxFriendAddNorequest
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendDelete
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFriendDelete
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendByPublicKey
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxFriendByPublicKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendGetPublicKey
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxFriendGetPublicKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendExists
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_im_tox_jtoxcore_JTox_toxFriendExists
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfGetFriendList
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_im_tox_jtoxcore_JTox_toxSelfGetFriendList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxSelfSetTyping
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxSelfSetTyping
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendSendMessage
 * Signature: (JIII[B)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxFriendSendMessage
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFileControl
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFileControl
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFileSeek
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFileSeek
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFileSend
 * Signature: (JIIJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_im_tox_jtoxcore_JTox_toxFileSend
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jbyteArray, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFileSendChunk
 * Signature: (JIIJ[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFileSendChunk
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFileGetFileId
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_im_tox_jtoxcore_JTox_toxFileGetFileId
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendSendLossyPacket
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFriendSendLossyPacket
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    toxFriendSendLosslessPacket
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_toxFriendSendLosslessPacket
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeSelfConnectionStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeSelfConnectionStatus
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFileRecvControl
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFileRecvControl
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFileRecv
 * Signature: (JIIIJ[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFileRecv
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFileRecvChunk
 * Signature: (JIIJ[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFileRecvChunk
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFileChunkRequest
 * Signature: (JIIJI)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFileChunkRequest
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendConnectionStatus
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendConnectionStatus
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendLosslessPacket
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendLosslessPacket
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendLossyPacket
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendLossyPacket
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendMessage
 * Signature: (JIII[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendMessage
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendName
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendName
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendRequest
 * Signature: (J[BI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendRequest
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendStatus
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendStatus
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendStatusMessage
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendStatusMessage
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendTyping
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendTyping
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     im_tox_jtoxcore_JTox
 * Method:    invokeFriendReadReceipt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_im_tox_jtoxcore_JTox_invokeFriendReadReceipt
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
